### ISSUE TITLE
Explore assistant not loading for users with User License

### ISSUE THREAD

**Issue by arun-subhash** [looker-open-source/looker-explore-assistant#61]
Hi 

We enabled explore assistant for our production environment. I was loading only for Admin users. We were getting a loading screen for users with an explore (user) license and didn't proceed to the prompt. 
On debugging we found that one of the resources was not responding for Explores - [/api/internal/core/4.0/sql_queries](https://instancename/api/internal/core/4.0/sql_queries)

To solve this We needed to enable - use_sql_runner permission for user license then it worked for Explores.  Since by default user role does not have - use_sql_runner is this necessary? As it might have cost implications and we don't want to give SQL runner to user license type.

image.png
![Screenshot 2024-07-03 at 5 01 40 PM](https://github.com/looker-open-source/looker-explore-assistant/assets/52467725/f5fb89a4-af42-4162-9034-d2e1c6dbdd77)

**Comment by LukaFontanilla** [comment]
@arun-subhash this currently is expected behavior. At a minimum a user needs to have a Standard User license to be able to access Explore Assistant. The default "User" role would roll up into the Standard User license but doesn't include all the permissions that a Standard User is entitled too. Our [legal terms](https://cloud.google.com/terms/looker/legal/customers/licensing) describe this in a bit more detail. But using SQL Runner is something that is permitted for the Standard User license.
